name: Zeno Update

on:
  workflow_dispatch:
  schedule:
    # Runs at every 1 min
    - cron: '*/20 * * * *'0

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    name: Check all sites
    steps:
      - uses: actions/checkout@v2
      - name: Run Shell Script
        id: shell_script_run
        run: bash ./health-check.sh
